//package logic;
//
//import java.io.FileNotFoundException;
//import java.io.FileOutputStream;
////import java.util.Date;
//import java.io.IOException;
//import java.net.MalformedURLException;
//import java.util.Date;
//
//import javax.swing.JOptionPane;
//
//import com.itextpdf.text.BaseColor;
//import com.itextpdf.text.Document;
//import com.itextpdf.text.DocumentException;
//import com.itextpdf.text.Element;
//import com.itextpdf.text.FontFactory;
//import com.itextpdf.text.Image;
//import com.itextpdf.text.Paragraph;
//import com.itextpdf.text.pdf.PdfPCell;
//import com.itextpdf.text.pdf.PdfPTable;
//import com.itextpdf.text.pdf.PdfWriter;
//
//public class Certificate_create {
//public static void main(String[] args) {
//		
//		Document document=new Document();
//		try {
//			//Source: using YouTube videos by user ProgrammingKnowledge, among others - https://www.youtube.com/watch?v=_4RN5EJNzTU
//			// source: https://stackoverflow.com/questions/31602859/getting-mysql-database-table-in-to-a-itext-pdf-report-in-java
//			//PdfWriter writer=PdfWriter.getInstance(document, new FileOutputStream("C:Users\\Charles\\git\\SoftwareProject2Groep9\\src\\PDFprintingText.pdf"));
//			PdfWriter writer=PdfWriter.getInstance(document, new FileOutputStream("..\\SoftwareProject2Groep9\\src\\PDFprintingText.pdf"));
//			writer.open();
//			document.open();
//			// begin addition: insert picture image into PDF document
//			document.add(new Paragraph("Image Title")); //--> is printed ok - no longer needed
//			Image image = Image.getInstance("..\\SoftwareProject2Groep9\\src\\image9.jpg");
//			document.add(image);
//			Paragraph paragraph = new Paragraph();
//
//			// document.add(new Paragraph("When will this work as expected?")); --> picture prints ok
//			document.add(new Paragraph("Hello Software Group 9",FontFactory.getFont(FontFactory.TIMES_BOLD)));
//			document.add(new Paragraph(new Date().toString()));
//			document.add(new Paragraph("-------------------------------"));
//			//start adding table
//			PdfPTable table = new PdfPTable(4);	
//			// 2 is number of columns
//			// start adding title to PDF - set columns - alignment - background color
//			PdfPCell cell = new PdfPCell(new Paragraph("Training Certificate"));
//			cell.setColspan(4);
//			cell.setHorizontalAlignment(Element.ALIGN_CENTER);
//			cell.setBackgroundColor(BaseColor.YELLOW);
//			table.addCell(cell);
//			table.addCell("Employee ID");
//			table.addCell(" new value1 ");
//			table.addCell("  ");
//			table.addCell("  ");
//			table.addCell("Certificate ID");
//			table.addCell(" value2 ");
//			table.addCell("Issue Date  ");
//			table.addCell("  ");
//			table.addCell("  ");
//			table.addCell("  ");
//			table.addCell("Expiration date");
//			table.addCell("  ");
//			document.add(table);			
//			// adds table to the report - end of table creation
//			// stop adding table
//			com.itextpdf.text.List list = new com.itextpdf.text.List();
//			list.add("First item in list");
//			list.add("Second item in list");
//			list.add("Third item in list");
//			list.add("Fourth item in list");
//			document.add(list);
//			//----------------
//			Paragraph preface = new Paragraph();
//			// Source: http://www.vogella.com/tutorials/JavaPDF/article.html
//			// Lets write a big header
//			preface.add(new Paragraph("Title of the document"));
//
//			// Will create: Report generated by: _name, _date
//			preface.add(new Paragraph(
//			"This document describes something which is very important "));
//
//			preface.add(new Paragraph(
//			"This document is a preliminary version and not subject to your license agreement or any other agreement with vogella.com ;-)."));
//			preface.add(new Paragraph(
//			"Report generated by: " + System.getProperty("user.name") + ", " + new Date())); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$));
//			document.add(preface);
//			//----------------
//// end addition - insert picture image into Pdf document
//			
//			document.add(new Paragraph("Nog's en keer proberen"));
//			document.close();
//			//begin addition
//			JOptionPane.showMessageDialog(null,  "Report Saved");
//			//end addition
//			writer.close();
//		}
//		catch(DocumentException e) {
//			e.printStackTrace();
//		}
//		catch(FileNotFoundException e) {
//			e.printStackTrace();
//		} catch (MalformedURLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (IOException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//	}
//
//}
